### ISSUE TITLE
how to upload image aws

### ISSUE THREAD

**Issue by shaikhussian** [PhilippKrone/react-native-fileupload#17]
i have a doubt that how to upload an image to amazons3 with this, For upload an image can i use this repo, if possible how to use it

**Comment by shaikhussian** [comment]
I tried like this 
`var credentials = {`
  SecretKey: 'secretKey',
    AccessKeyId: 'AccessKeyId',
    Bucket: 'fitvite-development',
    region:'us-west-2',
    type:'image/',
    path:'images',
    acl:'public-read'
}
var fileName = response.uri.substring(response.uri.lastIndexOf("/") + 1);
          var fsPath = response.uri;
          alert("fsPath:"+JSON.stringify(fsPath));
          console.log("fsPath:"+JSON.stringify(fsPath));
          var options = {
            path:response.uri,
            method:'post',
            service:'service',
            headers: {
                'X-Amz-Date': '20150209T123600Z',
                'host': 'https://xxxx.amazonaws.com/fitvite-development',
                'Accept': 'application/json',
                'ContentType':'image/jpg'
            },
           region:'us-west-2',
            body:JSON.stringify(fsPath),
            credentials
          };
          awsSignature.setParams(options);
          var signature = awsSignature.getSignature();
          var authorization = awsSignature.getAuthorizationHeader();
          alert("auth:"+JSON.stringify(authorization));
           var obj = {
            uploadUrl:'https://xxx.amazonaws.com/development',
            method:'POST',
            headers:{
              'Accept':'application/json'
            },
            fields:{
              "acl":credentials.acl,
              "Content-Type":"image/",
              "key":'biz/'+'third.jpg',
              'X-Amz-Signature': authorization.signature,
              'x-amz-credential': authorization.credential,
              'X-Amz-Algorithm': 'AWS4-HMAC-SHA256',
              'X-Amz-Date': authorization.date + 'T000000Z',
              'Content-Type': 'image/png',
              'policy': authorization.policy,
              'success_action_status': '201',
              'x-amz-meta-uuid': '14365123651274' // here which uuid i need to write
            },
            files:[
            {
            filename:fileName,
            filepath:response.uri,
            }
            ]
          }
          FileUpload.upload(obj, function(err,result){
            alert("upload:"+JSON.stringify(result));
            console.log("upload:", err, result);
          })
      }
    })`
but i am getting some error like  this 
![screen shot 2016-03-10 at 6 56 04 pm](https://cloud.githubusercontent.com/assets/11956308/13670834/3f4bb568-e6f2-11e5-9fc7-e91108fabd55.png)

**Comment by shaikhussian** [comment]
can you please respond for my issue

**Comment by timsuchanek** [comment]
@shaikhussian I'm trying to achieve the same.

So obviously AWS doesn't see the file under the key `file`.
Please try giving it additionally the key `name` with value `file`:

``` js
{
  name: 'file',
  filename: ...
}
```

I'm interested if that works for you.
Btw you can debug that by sending the same request to http://requestb.in/, which I'm using for debugging.
Because I did the `name: 'file'` thing, still the field is called "image".
How is your file field called if you debug it with requestbin?

**Edit:**
Stoop. This line of code is probably the problem:
https://github.com/PhilippKrone/react-native-fileupload/blob/master/android/src/main/java/com/yoloci/fileupload/FileUploadModule.java#L116
name=\"image\" needs to be name=\"file\"

Try to replace that.
I'll do tomorrow, it's late now.

**Comment by shaikhussian** [comment]
@timsuchanek thank you for your response, can you please provide the working example for AWS, I am waiting for it

**Comment by timsuchanek** [comment]
Hey @shaikhussian, you can either use my fork https://github.com/timsuchanek/react-native-fileupload or one of the other two forks which resolved the same issue.
How you handle the S3 signing stuff etc is your choice, I use boto3 from python, because I have a python backend. But surely for any major language solutions exist.
